---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/gradle
    tag: "2.14"

inputs:
- name: spring-music

outputs:
- name: built-spring-music

run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    gradle -v
    gradle test build -p ./spring-music
    mkdir -p ./built-spring-music/build/libs
    cp ./spring-music/build/libs/spring-music.jar ./built-spring-music/build/libs/
    cp ./spring-music/manifest.yml ./built-spring-music/
