---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/gradle
    tag: "2.14"

inputs:
- name: spring-music

outputs:
- name: built-spring-music
  path: ./spring-music

run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    gradle -v
    gradle test build -p ./spring-music
