---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: heroku/gradle
    tag: latest

inputs:
- name: spring-music

run:
  path: sh
  args:
  - -exc
  - |
    ls -la
    ls -la ./spring-music
    export TERM=${TERM:-dumb}
    ./spring-music/gradlew build
