---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/gradle
    tag: 2.14

inputs:
- name: spring-music
- name: concourse-servicenow-pipeline

run:
  path: sh
  args:
  - -exc
  - |
    export TERM=${TERM:-dumb}
    gradle -v
    cd ./spring-music && gradle build
